allowBuilds:
  '@parcel/watcher': true
  core-js: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - msw
overrides:
  typescript: "^6.0.3"
